"""
Modal.com Host Utilities

Utilities for deploying ComfyUI to Modal.com serverless platform.
This module provides helper functions and configuration for Modal deployments.
"""

import os
import logging
from typing import Dict, Optional, Any
from pathlib import Path

logger = logging.getLogger(__name__)


def get_modal_comfyui_config(
    models_volume_name: str = "comfyui-models",
    outputs_volume_name: str = "comfyui-outputs",
    gpu_config: str = "A10G",
    timeout: int = 600,
    scaledown_window: int = 300
) -> Dict[str, Any]:
    """
    Get configuration for Modal ComfyUI deployment.
    
    Args:
        models_volume_name: Name of the Modal volume for models
        outputs_volume_name: Name of the Modal volume for outputs
        gpu_config: GPU configuration (e.g., "A10G", "T4")
        timeout: Function execution timeout in seconds
        scaledown_window: Container idle time before scaling down (seconds)
    
    Returns:
        Dictionary with Modal configuration
    """
    return {
        'models_volume_name': models_volume_name,
        'outputs_volume_name': outputs_volume_name,
        'gpu_config': gpu_config,
        'timeout': timeout,
        'scaledown_window': scaledown_window,
        'headless': True,
    }


def create_modal_comfyui_app(
    app_name: str = "comfyui-api",
    comfyui_root: Optional[str] = None,
    **config
) -> str:
    """
    Generate a Modal app configuration for ComfyUI.
    
    This function returns Python code that can be used to create a Modal app.
    For actual deployment, users should create their own Modal app file.
    
    Args:
        app_name: Name of the Modal app
        comfyui_root: Path to ComfyUI root directory (defaults to current)
        **config: Additional configuration (see get_modal_comfyui_config)
    
    Returns:
        String containing Modal app code template
    """
    if comfyui_root is None:
        comfyui_root = os.getcwd()
    
    modal_config = get_modal_comfyui_config(**config)
    
    template = f'''"""
ComfyUI Modal Deployment

Generated by ComfyUI Serverless Plugin.
This file provides a template for deploying ComfyUI to Modal.com.

Usage:
    modal deploy {app_name}_modal.py
"""

import modal
import os
from pathlib import Path

# Import serverless utilities
from custom_nodes.comfyui_serverless.serverless.headless_utils import setup_headless_environment
from custom_nodes.comfyui_serverless.integrations.civitai import CivitaiModelManager
from custom_nodes.comfyui_serverless.integrations.huggingface import HuggingFaceModelManager

# Modal app configuration
app = modal.App("{app_name}")

# Get ComfyUI root
COMFYUI_ROOT = Path("{comfyui_root}").resolve()

# Build container image
base_image = (
    modal.Image.debian_slim(python_version="3.11")
    .apt_install(
        "git", "wget", "curl", "build-essential",
        "libglib2.0-0", "libsm6", "libxext6", "libxrender-dev",
        "libgomp1", "libgl1-mesa-glx",
    )
    .pip_install(
        "torch", "torchvision", "torchaudio",
        index_url="https://download.pytorch.org/whl/cu121"
    )
)

image = (
    base_image
    .pip_install(
        "torchsde", "numpy>=1.25.0", "einops",
        "transformers>=4.37.2", "tokenizers>=0.13.3",
        "sentencepiece", "safetensors>=0.4.2",
        "aiohttp>=3.11.8", "yarl>=1.18.0", "pyyaml",
        "Pillow", "scipy", "tqdm", "psutil",
        "python-dotenv>=1.0.0", "alembic", "SQLAlchemy",
        "av>=14.2.0", "kornia>=0.7.1", "spandrel",
        "soundfile", "pydantic~=2.0", "pydantic-settings~=2.0",
        "fastapi[standard]", "requests",
        "huggingface_hub",  # For HuggingFace integration
    )
    .add_local_dir(
        str(COMFYUI_ROOT),
        remote_path="/app",
        copy=False,
        ignore=[
            "models/**", "output/**", "input/**",
            "**/__pycache__/**", "**/*.pyc",
            ".git/**", "tests/**", "docs/**",
        ]
    )
)

# Persistent volumes
models_volume = modal.Volume.from_name("{modal_config['models_volume_name']}", create_if_missing=True)
outputs_volume = modal.Volume.from_name("{modal_config['outputs_volume_name']}", create_if_missing=True)

# GPU and timeout configuration
GPU_CONFIG = "{modal_config['gpu_config']}"
TIMEOUT = {modal_config['timeout']}
SCALEDOWN_WINDOW = {modal_config['scaledown_window']}


@app.function(
    image=image,
    gpu=GPU_CONFIG,
    timeout=TIMEOUT,
    scaledown_window=SCALEDOWN_WINDOW,
    volumes={{
        "/models": models_volume,
        "/outputs": outputs_volume,
    }},
)
@modal.asgi_app()
def web():
    """FastAPI app that runs ComfyUI in headless mode"""
    import sys
    sys.path.insert(0, "/app")
    
    from fastapi import FastAPI, HTTPException
    from fastapi.responses import JSONResponse
    from pydantic import BaseModel
    import uuid
    import json
    
    # Configure headless mode BEFORE importing ComfyUI
    setup_headless_environment()
    os.environ['COMFYUI_MODEL_PATH'] = '/models'
    os.environ['COMFYUI_OUTPUT_PATH'] = '/outputs'
    
    # Import and configure ComfyUI
    import folder_paths
    folder_paths.set_output_directory('/outputs')
    
    # Configure model directories
    model_dirs = {{
        "checkpoints": "/models/checkpoints",
        "vae": "/models/vae",
        "loras": "/models/loras",
        "controlnet": "/models/controlnet",
        "clip_vision": "/models/clip_vision",
        "upscale_models": "/models/upscale_models",
        "embeddings": "/models/embeddings"
    }}
    
    for category, path in model_dirs.items():
        os.makedirs(path, exist_ok=True)
        folder_paths.add_model_folder_path(category, path, is_default=True)
    
    # Import ComfyUI main
    import main
    import execution
    
    # Configure for headless mode
    from comfy.cli_args import args
    args.headless = True
    
    # Initialize ComfyUI
    event_loop, prompt_server, _ = main.start_comfyui()
    event_loop.run_until_complete(prompt_server.setup())
    
    # Create FastAPI app
    web_app = FastAPI(
        title="ComfyUI API on Modal",
        description="Serverless ComfyUI API powered by Modal",
        version="1.0.0"
    )
    
    class PromptRequest(BaseModel):
        prompt: dict
        client_id: str | None = None
    
    @web_app.get("/")
    async def root():
        return {{
            "name": "ComfyUI on Modal",
            "status": "running",
            "endpoints": {{
                "POST /prompt": "Queue a workflow",
                "GET /queue": "Get queue status",
                "GET /history": "Get execution history",
            }}
        }}
    
    @web_app.post("/prompt")
    async def queue_prompt(request: PromptRequest):
        """Queue a ComfyUI workflow for execution"""
        try:
            prompt_id = str(uuid.uuid4())
            
            valid = await execution.validate_prompt(prompt_id, request.prompt, None)
            if not valid[0]:
                return {{
                    "error": f"Invalid workflow: {{valid[1]}}",
                    "valid": False
                }}
            
            outputs_to_execute = valid[2]
            extra_data = {{}}
            if request.client_id:
                extra_data["client_id"] = request.client_id
            
            number = prompt_server.number
            prompt_server.number += 1
            
            prompt_server.prompt_queue.put((number, prompt_id, request.prompt, extra_data, outputs_to_execute))
            
            return {{
                "prompt_id": prompt_id,
                "number": number,
                "valid": True,
                "message": "Workflow queued. Use GET /history/{{prompt_id}} to check status."
            }}
        except Exception as e:
            raise HTTPException(status_code=500, detail=str(e))
    
    @web_app.get("/queue")
    async def get_queue():
        """Get current queue status"""
        try:
            current_queue = prompt_server.prompt_queue.get_current_queue_volatile()
            return {{
                "queue_running": current_queue[0],
                "queue_pending": current_queue[1]
            }}
        except Exception as e:
            raise HTTPException(status_code=500, detail=str(e))
    
    @web_app.get("/history")
    async def get_all_history():
        """Get all execution history"""
        try:
            history = prompt_server.prompt_queue.get_history()
            return history
        except Exception as e:
            raise HTTPException(status_code=500, detail=str(e))
    
    return web_app


@app.local_entrypoint()
def main():
    """Local entrypoint"""
    print("ComfyUI Modal Deployment")
    print("=" * 50)
    print("\\nTo deploy:")
    print(f"  modal deploy {app_name}_modal.py")
    print("\\nYour endpoint will be:")
    print(f"  https://{{workspace}}--{app_name}-web.modal.run")
'''
    
    return template


def validate_modal_setup() -> Dict[str, Any]:
    """
    Validate Modal setup and return status.
    
    Returns:
        Dictionary with validation results
    """
    results = {
        'modal_installed': False,
        'modal_authenticated': False,
        'errors': []
    }
    
    try:
        import modal
        results['modal_installed'] = True
        
        # Try to check authentication
        try:
            # This will fail if not authenticated
            modal.app.App.from_name("test", create_if_missing=False)
            results['modal_authenticated'] = True
        except Exception:
            results['errors'].append("Modal not authenticated. Run 'modal token new'")
    except ImportError:
        results['errors'].append("Modal SDK not installed. Install with: pip install modal")
    
    return results

